import ru.mpei.brics.extention.dto.DroolsFrequencyFitnessDto;
import jade.core.Agent;

rule "load1 active power deficit fitness calculation"
    when
        $dto: DroolsFrequencyFitnessDto(agentName == "load1", currentFreq < 50)
    then
        $dto.setFitnessVal(10 * ($dto.getCurrentP() / $dto.getMaxP()));
end

rule "load1 active power surplus fitness calculation"
    when
        $dto: DroolsFrequencyFitnessDto(agentName == "load1", currentFreq > 50)
    then
        $dto.setFitnessVal(10 * (1- $dto.getCurrentP() / $dto.getMaxP()));
end
