import ru.mpei.brics.model.KnowledgeBaseFitnessDto;
import ru.mpei.brics.model.KnowledgeBaseAllowDto;
import jade.core.Agent;

rule "load1 active power deficit fitness calculation"
    when
        $dto: KnowledgeBaseFitnessDto(currentFreq < 50)
    then
        $dto.setFitnessVal(10 * ($dto.getCurrentP() / $dto.getMaxP()));
end

rule "load1 active power surplus fitness calculation"
    when
        $dto: KnowledgeBaseFitnessDto(currentFreq > 50)
    then
        $dto.setFitnessVal(10 * (1- $dto.getCurrentP() / $dto.getMaxP()));
end

rule "load1 allow signal"
    when
        $dto: KnowledgeBaseAllowDto(currentP <= maxP && currentP >= 0)
    then
        $dto.setAllow(true);
end