import ru.mpei.brics.model.KnowledgeBaseFitnessDto;
import ru.mpei.brics.model.KnowledgeBaseAllowDto;
import jade.core.Agent;

rule "station2 active power deficit fitness calculation"
    when
        $dto: KnowledgeBaseFitnessDto(currentFreq < 50)
    then
        $dto.setFitnessVal(10 * (1- $dto.getCurrentP() / $dto.getMaxP()) + 10);
end

rule "station2 active power surplus fitness calculation"
    when
        $dto: KnowledgeBaseFitnessDto(currentFreq > 50)
    then
        $dto.setFitnessVal(10 * ($dto.getCurrentP() / $dto.getMaxP()) + 10);
end

rule "station2 allow signal"
    when
        $dto: KnowledgeBaseAllowDto(currentP <= maxP && currentP >= 0)
    then
        $dto.setAllow(true);
end